### ISSUE TITLE
Issues with voice/sound

### ISSUE THREAD

**Issue by IggyDinosaur** [breadweb/extralife-helper#11]
Greetings,

I was checking out your extra life tool and ran into a few issues.

https://code.responsivevoice.org/getvoice.php?t=This is such a good cause. Good luck!&tl=en-GB&sv=g1&vn=&pitch=0.5&rate=0.5&vol=1&gender=female
Resolves to a 403 address and won't play sounds

Donations text to speech also seems to not work in OBS.  It will play the sound, but not read the donation.  

However, if I just load the html file in a browser, it plays the text to speech, if I pick US-male, but it will not play sounds.

**Comment by breadweb** [comment]
Thank you! I can confirm speech to text is not working when running in OBS. Will try to fix this weekend. 

Unfortunately, when running in a normal browser, the sound effects won't play unless you've interacted with the helper first by clicking on it somewhere with your mouse. Since the main use case is to use the helper in OBS, probably won't have a fix for that soon.

**Comment by breadweb** [comment]
This is fixed for both the download version and remote version. Thanks again for the report!
