### ISSUE TITLE
Add ability to remove both time until and year

### ISSUE THREAD

**Issue by EpicFail113** [breadweb/extralife-helper#12]
I really like the plugin and this will be my second year using it. I wanted to make the suggestion to add the ability to remove the year and 'time until' feature to make the whole thing a little more compact.

**Comment by breadweb** [comment]
Hey there. Are you suggesting a mode where the Helper only shows your total and does not include the count up/down timers?  By compact, do you mean that you'd just not like to see that timer information or that you'd like the helper to render at a smaller size?

**Comment by EpicFail113** [comment]
Correct, everyone has different dates they do their "game day" on so the ability to remove the counter would be great. Removing the date/time would also then give more room for either the donation/total raised or allow for the whole counter to be a smaller more compact size.

**Comment by breadweb** [comment]
On the note of everyone having a different game day, you can control this by changing the start date and time. It can be set to whatever you would like and changed as many times as you would like. 

But if your goal is to simply remove the timer / year display because they're not useful to you, I can definitely consider that as an option for a future release.  In the meantime, if you or anyone you know has a little JavaScript experience, you can certainly remove the timer yourself in the downloadable version. Thanks!
