### ISSUE TITLE
Progress doubles when receiving donation during stream

### ISSUE THREAD

**Issue by TheW1ldG1nger** [breadweb/extralife-helper#22]
Hi! I love this tool and have used it for as long as I can remember doing Extra Life (which means maybe 10 years if it's been around that long?). 

Twice this year, we've noticed that when someone has donated during a stream, it looks like it's adding the old total to the new total rather than adding the most recent donation to the old total. 

My buddy clipped it this last time, where I was at $740, received a $30 donation, and it displayed the total as $1510 (which is 740+770): 
https://www.twitch.tv/thew1ldg1nger/clip/CarelessApatheticYogurtSeemsGood-rN6v4iEmfm-MmrGy

**Comment by breadweb** [comment]
That is definitely a weird issue and it's the first I've heard or seen of it! Thanks for the report and for the clip. I'll see if I can reproduce. In the meantime can you please ensure you're using the latest version of the Helper by clearing the cache of your browser source?

**Comment by TheW1ldG1nger** [comment]
Thanks for the quick reply! Haven't had a chance to stream this week, so I'm trying it out now and will let ya know :)

**Comment by breadweb** [comment]
The issue was reported by another user of the Helper and I'm looking to have a fix soon!

**Comment by breadweb** [comment]
@TheW1ldG1nger just checking in to see if you've noticed issue again. Also when the issue happened last time, did the incorrect total get corrected automatically after about 15 seconds?

**Comment by TheW1ldG1nger** [comment]
Yep, it has continued occurring :( I haven't let the Helper sit for 15 secs, I don't think. I noticed that in Streamlabs, if I clear the cache for the Helper's source it immediately corrects to the right value. So, I've done that pretty quick after noticing each time. 

I also noticed that if I paste the link generated by the Helper directly into a browser, it shows the right value.

I did also try logging in and out of my Twitch account on Streamlabs just to try something, but that didn't seem to make a difference.

**Comment by breadweb** [comment]
Thanks for the extra info. Only one other report for this specific issue has been made and for this to be happening consistently for you is very strange. The source of the bug is not obvious and I haven't been able to reproduce yet. 

When you say that you don't see the issue in a browser, does that include when you get donations? The total doesn't double after the donation alert in the browser? Curious if you had both running at the same time where the instance in Streamlabs doesn't work but the browser works.

Also, you're using Streamlabs OBS? If so can you please tell me what version? If you're a version behind and are in an OK position to upgrade, that might be a good idea. 

Also, are you adding the Helper as a browser source, or is there some other scene design that you're doing on the Streamlabs website to get the Helper part of your scene?

**Comment by TheW1ldG1nger** [comment]
Good questions! I'll try some of this out when I get home later. 

I haven't had the Helper open separately in a browser at the time of receiving a donation, so I can try that out. I've only opened the Helper link in a browser after seeing the donation double, so I haven't really had both running simultaneously. 

I'm using Streamlabs desktop (i.e. not on top of OBS). I'm supposedly using the most recent version, but I can double check when home. 

I was using the Helper as a browser source.

**Comment by TheW1ldG1nger** [comment]
I got it working for me!

It looks like enabling Donation Alerts is allowing it to calculate the right amount. Maybe because it redraws everything after the donation alert displays?

Here's what I did:
- Validated that copying the link into a Google Chrome was showing the same behavior as on Streamlabs Desktop (both were doubling)
- Cleared my Chrome cache again and logged out/in of Streamlabs Desktop (and Streamlabs.com)
- Generate a new Helper link
- I set Donation Alerts to Disabled --> Was able to recreate the doubling issue.
- I generated a new Helper link with Donation Alerts Enabled --> Everything worked (i.e. no doubling!)
- I generated third Helper link with Donation Alerts Disabled again --> The doubling issue happened again.

I finally generated a 4th Helper link with Donation Alerts Enabled, and it looks like things are working. I had originally disabled them because I show an alert on stream already, but it's really not a big deal to have the Helper show it, too :) 

So I'm cool if ya close this, but I figured I'd leave it open in case you wanted to try that out. Hope you have a great weekend (especially if you're playing on Game Day!!!)

**Comment by breadweb** [comment]
@TheW1ldG1nger Thank you so much for all of those details, that's super helpful! It is rare for folks to turn off donation alerts so that makes sense why the bug hasn't been reported by more than you and one other person. I should have asked you for your link or settings...

I am able to reproduce the issue now so there is a good chance I can get a fix in tonight as long as I'm all finished setting up for Extra Life weekend. I'll close this thread after the bug is fixed and deployed. Thanks again!

**Comment by breadweb** [comment]
The fix has been deployed. You can now run the Helper with donation alerts turned off and the total will not incorrectly double. It will increase to the new amount raised and animate correctly.
